name: s_push_notifications_example
description: Demonstrates how to use the s_push_notifications plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # S-PushNotify
  s_push_notifications:
    path: ../
  #
  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
