name: s_push_notifications
description: A new Flutter plugin project.
version: 0.1.3
homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  # S-PushNotifications
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.s_push_notifications
        pluginClass: SPushNotificationsPlugin
      ios:
        pluginClass: SPushNotificationsPlugin
