// android/build.gradle del paquete s_push_notifications

plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group 'com.example.s_push_notifications'
version '1.0-SNAPSHOT'

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace "com.example.s_push_notifications" // cambiá al tuyo real si querés
    compileSdk 35

    defaultConfig {
        minSdk 21 // o 24 si querés alinear con proyectos nuevos
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17   // si tu app compila con 17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }
}

// 👇 OJO: este bloque va FUERA de `android { }`
dependencies {
    // implementation "org.jetbrains.kotlin:kotlin-stdlib"  // (opcional)
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.mockito:mockito-core:5.0.0'
}
